- lib/command.js
- spec/command_spec.js
Jasmine's output is a bit of a mess when it's piped or redirected. Although users can already get around the problem by passing --no-color, a well-behaved command line program should take care of this sort of thing automatically.
Here's what piping to less looks like before this change:
```Started
ESC[32m.ESC[0mESC[32m.ESC[0mESC[32m.ESC[0mESC[32m.ESC[0mESC[32m.ESC[0mESC[32m.
ESC[0mESC[32m.ESC[0mESC[32m.ESC[0mESC[32m.ESC[0mESC[32m.ESC[0mESC[32m.ESC[0mESC[32m.ESC[0mESC[32m.ESC[0mESC[32m.ESC[0mESC[32m.ESC[0mESC[32m.ESC[0mESC[32m.ESC[0mESC[32m.ESC[0mESC[32m.ESC[0mESC[32m.ESC[0mESC[32m.ESC[0mESC[32m.ESC[0mESC[32m.
ESC[0mESC[32m.ESC[0mESC[32m.ESC[0mESC[32m.ESC[0mESC[32m.ESC[0mESC[32m.ESC[0mESC[32m.ESC[0mESC[32m.ESC[0mESC[32m.ESC[0mESC[32m.ESC[0mESC[32m.ESC[0mESC[32m.ESC[0mESC[32m.ESC[0mESC[32m.E …
```
> Don't output ANSI escape sequences if stdout is not a terminal

- lib/command.js
- lib/filters/console_spec_filter.js
- lib/jasmine.js
- spec/command_spec.js
- spec/filters/console_spec_filter_spec.js
- spec/jasmine_spec.js
- spec/support/jasmine.json
That is exactly looks like [HtmlSpecsFilter](https://github.com/jasmine/jasmine/blob/master/src/html/HtmlSpecFilter.js) does.
Usage example:
```
jasmine --filter="some spec"
```
It's better than already existing filtering by file, because it allows to extract some specs from instead of whole file.
> Add filter by spec name

- lib/reporters/console_reporter.js
- spec/reporters/console_reporter_spec.js
Related to https://github.com/jasmine/jasmine-npm/issues/45.
If there are any disabled specs (or, more accurately, specs which are not passed, failed, or pending) then report line `Ran X of Y specs`, like the ruby gem reporter.
> Report "Ran X of Y specs" if some are disabled.

- tasks/jasmine.js
in order to follow the same API as the executable
> use JASMINE_CONFIG_PATH env in grunt task

- lib/command.js
- lib/jasmine.js
- lib/reporters/console_reporter.js
- spec/command_spec.js
- spec/jasmine_spec.js
- spec/reporters/console_reporter_spec.js
This is a follow up of jasmine/jasmine#927 it enables the `--random` and `--seed` flags in the cli.
A `random` option is also loaded from jasmine.json for these who want to change the default behaviour and use random tests by default.
> Enable the --random and --seed cli flags

- lib/jasmine.js
- spec/jasmine_spec.js
Motivation:
In full disclosure I am re-writing a plugin that I maintain [gulp-jasmine-phantom](https://github.com/dflynn15/gulp-jasmine-phantom) to use `jasmine-npm` instead of `minijasminenode` as it has become stale and does not include the full features that you all have worked so hard to make available to us. 
After playing with it I quickly realized that the `spec_dir` parameter was _required_ in the configuration in order to run `jasmine.execute()`. Adding this mandatory option felt unnecessary as you can provide full file paths, or even shortened ones, to Jasmine without it needing to know about your directory structure. Node's internal `path.resolve` and `path.join` will already handle the merge of any odd directory structures and does not need to understand how we place specs in …
> fix: Makes `spec_dir` optional

- lib/jasmine.js
- spec/helpers/console_reporter.js
- spec/jasmine_spec.js
Hi there,
I've opened  https://github.com/jasmine/jasmine/pull/1009 in jasmine-core to allow configuring a fallback report in case there's no report configured. It would allow configuring a reporter in a helper as follows:
```node
jasmine.getEnv().addReporter(myReporter);
```
It would deal with issue #66 opened by myself.
Sorry if I've missed something. Thanks and regards!
> Changes the default report configuration, using fallback instead

- lib/jasmine.js
- spec/jasmine_spec.js
> Only use the default exiting if the default reporter is used

- spec/helpers/console_reporter.js
Using a specific reporter in this repository tests hide the fact default reporter is never used, cf #90.
> Use default reporter in this repository tests

- lib/filters/console_spec_filter.js
Currently there is no way for the user to filter (`--filter`) using a regex pattern. This is due to the current implementation automatically escaping the passed filter parameter. This tiny PR enables the user to filter using a regex pattern. It is better for the following reasons:
- Enables the user to decide whether to pass a regex pattern or a normal string (manual escape).
- Simplifies the implementation as there is no need to cover all possible special regex characters. But most importantly,
- Allows running specific modules/tests. For example:
```javascript
it('math', function() {
...
});
it('discrete math', function() {
...
});
describe('math equations', function() {
...
});
```
With the current implementation, `jasmine --filter='math'` will test all three, and `jasmine …
> Enable regex filter by omitting automatic escaping

- lib/reporters/console_reporter.js
- spec/reporters/console_reporter_spec.js
> Fix #83 - default console reporter hangs sometimes

- MIT.LICENSE
Would you consider adding an explicit license file to this project?
The one in this pull request is just a suggestion. It's a copy of one from another one of your repos, with the start year changed to match the first commit for this project.
https://github.com/jasmine/jasmine/blob/master/MIT.LICENSE
Thanks.
> adding license file

- lib/jasmine.js
- spec/jasmine_spec.js
This is the naïve fix for https://github.com/jasmine/jasmine-npm/issues/95 as it appears @cnishina is working on a different but related problem.
> Don't call configureDefaultReporter in execute if it was already called.

- lib/reporters/console_reporter.js
- spec/reporters/console_reporter_spec.js
- move default values for setOptions to the var when defined
- setOptions to the ConsoleReporter if it exists on the options param
- test setOptions should not override existing options if set multiple times
closes #95
> Fix setOptions to the ConsoleReporter if it exists on the options param

- lib/command.js
- spec/command_spec.js
```sh
$ jasmine --some-option --another-option
Unknown options: --some-option, --another-option
Usage: jasmine [command] [options] [files]
Commands:
...
```
> Fix #53 - Reject unknown options

- README.md
- lib/command.js
- spec/command_spec.js
Usage:
`--config=	path to your optional jasmine.json`
> Fix #85 - Option to specify path to your jasmine.json

- lib/jasmine.js
- spec/jasmine_spec.js
- Call correct `addReporter` in constructor to keep track of
`reportersCount`
- Expose `closeReporters` from `env` and keep track of `reportersCount`
- Fixes jasmine/jasmine#1228
> Expose `closeReporters` methods in the wrapper

- lib/command.js
- spec/command_spec.js
`jasmine` automatically turns off colors when its output target is not tty, while it only has `--no-color` option which forces jasmine **not** to color its result.
However, when redirecting its result through non-tty to tty, colors should be retained.
This patch adds `--force-color` option, which forces jasmine to color its result, regardless of its output target (tty or non-tty).
> Add --force-color option

- lib/command.js
- spec/command_spec.js
Fix https://github.com/jasmine/jasmine-npm/issues/137 (by setting the exitCode to `1` if unknown options are present).
Modify `Command` so that `process.exitCode` is set to `1` if unknown options are present.
There's a couple different places you could do this, but this seems most reasonable -- the way all existing error codes work is that `bin/jasmine.js` expects to _reach the end of file_, and then handle exit codes via the exit trap.  In our case, `runJasmine` is never called, so there will be no exit trap, but just setting exitCode and allowing the process to exit naturally gives an execution flow most similar to the existing flow.
> Unknown command line options produce exit code 1

- lib/jasmine.js
- spec/jasmine_spec.js
Paths in spec_files and helpers starting with ! will be excluded
from respectively spec files and helper files.
#128
> Allow excluding spec files and helper files

- lib/jasmine.js
- spec/jasmine_spec.js
to prevent output cropping when jasmine is called from another process.
Cropping happens in some environments more often than others (might depend on shell).
Mostly happens when there is plenty of (error) output in buffer so it's not all flushed before process exit and is lost.
Same problem was in `jasmine-node`:
https://github.com/mhevery/jasmine-node/pull/420
Fix in that and in this PR is based on similar issue in mocha: https://github.com/mochajs/mocha/issues/333
> Wait until streams are completed before exiting

- lib/jasmine.js
- lib/reporters/completion_reporter.js
- package.json
- spec/jasmine_spec.js
- spec/reporters/completion_reporter_spec.js
Currently jasmine-npm does not remove the exit listener it adds when it executes. This pull moves the exit listener code completely within the completion reporter so that the listener can be added and removed whenever jasmine is started and done. This is basically pull #125 , except that the jasmine interface remains as intact as possible. The only interface change is that the completion reporter now uses jasmineStarted to add the exit listener. The jasmineStarted method can no longer be overwritten without losing the exit check logic. You can close issue #134 after merging. The fix should allow jasmine to be used with things like gulp watch without errors about max listeners.
Unfortunatly I also had to make failing tests pass on Windows since file logic relied on path separators only …
> Remove listener

- lib/command.js
- spec/command_spec.js
To allow for classic getopts argv parsing, one could now use `--` also to separate arguments meant for the process from the ones for the subprocess (here, the tests run by jasmine).
So now, one could do `node jasmine.js -- test-specific-arguments`.
A nicer fix would be to provide the extracted subprocess arguments via a specific arguments list, such as `jasmine.argv`, to avoid redoing part of parsing.
> not parsing argv after --

- lib/jasmine.js
- lib/reporters/console_reporter.js
- spec/jasmine_spec.js
- spec/reporters/console_reporter_spec.js
This adds support for `failSpecWithNoExpectations` when calling loadConfig() or in jasmine.json.
It also modifies the default ConsoleReporter to print 'Spec has no expectations' when `failSpecWithNoExpectations=true` and a spec with no expect() is found.
Documentation update is here: https://github.com/jasmine/jasmine.github.io/pull/127
- Fixes #156
> Support 'failSpecWithNoExpectations' config option

- lib/command.js
Fixes https://github.com/jasmine/jasmine-npm/issues/189 by using the pre-configured `jasmine.loader` when available to load the reporter.
> use the configured loader to load the reporter

- lib/command.js
- spec/command_spec.js
addHelperFiles() was removed in 28f9495544. Fixes #197.
> Change addHelperFiles() call to addMatchingHelperFiles()

- lib/loader.js
- spec/loader_spec.js
[Serenity/JS](https://serenity-js.org) provides a Jasmine adapter published as a namespaced module [`@serenity-js/jasmine`](https://serenity-js.org/api/jasmine/).
This change adds support for Jasmine `loader.js` to load namespaced modules and closes #199.
> Fixed support for namespaced modules. Closes #199
